apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contd.fullname" . }}-config
  labels:
    {{- include "contd.labels" . | nindent 4 }}
data:
  CONTD_LOG_LEVEL: {{ .Values.contd.logLevel | quote }}
  CONTD_METRICS_ENABLED: {{ .Values.contd.metricsEnabled | quote }}
  CONTD_TRACING_ENABLED: {{ .Values.contd.tracingEnabled | quote }}
  CONTD_S3_BUCKET: {{ .Values.contd.s3.bucket | quote }}
  CONTD_S3_REGION: {{ .Values.contd.s3.region | quote }}
